# Introdução

## Bases de dados

Os dados considerados nas aplicações deste livro são provenientes do Sistema de Informação da Vigilância Epidemiológica da Gripe (SIVEP-Gripe), sistema oficial para o registro dos casos e óbitos por Síndrome Respiratória Aguda Grave (SRAG) disponibilizado pelo Ministério da Saúde. Os dados correspondem a registros de gestantes e puérperas de 10 a 55 anos hospitalizadas com SRAG por COVID-19 confirmada por teste de PCR. Também é utilizados o conjunto de dados do Sistema de Informação sobre Nascidos Vivos (SINASC) obtido por meio da Plataforma de Ciência de Dados aplicada à Saúde (PCDaS) da Fundação Oswaldo Cruz (Fiocruz). Os conjuntos de dados são utilizado para ilustrar e demonstrar diversos aspectos dos conceitos abordados no texto, e podem ser baixados em <https://github.com/observatorioobstetrico/dados_livro_cd_saude>.

### Dados de COVID-19 em gestantes e puérperas

Essa base consiste em 11.523 registros de gestantes e puérperas diagnosticadas com COVID-19 no período de março de 2020 a dezembro de 2021. Alguns estudos conduzidos pelo OOBr usaram esses dados, dentre os quais podem ser citados: [Características demográficas e epidemiológicas sobre mulheres grávidas e puérperas que morreram de Síndrome Respiratória Aguda Grave no Brasil](https://observatorioobstetricobr.org/publicacoes/caracteristicas-demograficas-e-epidemiologicas-sobre-mulheres-gravidas-e-puerperas-que-morreram-de-sindrome-respiratoria-aguda-grave-no-brasil/), [Mortalidade materna associada à COVID-19 no Brasil em 2020 e 2021: comparação com mulheres não grávidas e homens](https://observatorioobstetricobr.org/publicacoes/desfechos-da-covid-19-em-puerperas-gestantes-e-mulheres-nao-gestantes-e-nem-puerperas-hospitalizadas/) e [Desfechos da COVID-19 em puérperas, gestantes e mulheres não gestantes e nem puérperas hospitalizadas](https://observatorioobstetricobr.org/publicacoes/desfechos-da-covid-em-puerperas-gestantes-mulheres-nao-gestantes-nao-puerperas/).

O dicionários das variáveis a ser considerado neste livro está na @tbl-covid19.

| Variável   | Descrição                                                                                                    | Valores                                                                                                                                                                          |
|------------------|---------------------|----------------------------------|
| DT_NOTIFIC | Data de preenchimento da ficha de notificação                                                                | Dia/Mês/Ano                                                                                                                                                                      |
| DT_SIN_PRI | Data de primeiros sintomas do caso                                                                           | Dia/Mês/Ano                                                                                                                                                                      |
| DT_NASC    | Data de nascimento da gestante ou puérpera                                                                   | Dia/Mês/Ano                                                                                                                                                                      |
| DT_INTERNA | Data em que gestante ou puérpera foi hospitalizada                                                           | Dia/Mês/Ano                                                                                                                                                                      |
| SEM_PRI    | Semana epidemiológica do início dos sintomas                                                                 | 1 a 52                                                                                                                                                                           |
| CS_RACA    | Raça da gestante ou puérpera                                                                                 | 1- branca; 2- preta; 3- amarela; 4- parda; 5-indígena; 9- ignorado                                                                                                               |
| CS_ESCOL_N | Nível de escolaridade da gestante ou puérpera                                                                | 0- sem escolaridade (analfabeto); 1- fundamental 1° ciclo (1ª a 5ª série); 2- fundamental 2 (6ª a 9ª série); 3- medio (1° ao 3° ano); 4- superior; 5- não se aplica; 9- ignorado |
| idade      | Idade, em anos, da gestante ou puérpera                                                                      | 10 a 55                                                                                                                                                                          |
| CS_GESTANT | Momento gestacional ou puerpério                                                                             | 1- 1° trimestre; 2- 2° trimestre; 3- 3° trimestre; 4- idade gestacional ignorada; 5- não; 9- ignorado                                                                            |
| PUERPERA   | Se paciente é puérpera ou parturiente (mulher que pariu recentemente - até 45 dias do parto)                 | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| SG_UF      | Sigla do estado de residência da gestante ou puérpera                                                        | Sigla padronizada pelo IBGE                                                                                                                                                      |
| ID_MN_RESI | Nome do município de residência da gestante ou puérpera                                                      | Nomes padronizados pelo IBGE                                                                                                                                                     |
| CO_MUN_RES | Código do município de residência da gestante ou puérpera                                                    | Código definido pelo IBGE                                                                                                                                                        |
| CS_ZONA    | Tipo de zona de residência da gestante ou puérpera                                                           | 1- urbana; 2- rural; 3- periurbana; 9- ignorado                                                                                                                                  |
| FEBRE      | Se gestante ou puérpera manifestou sintoma de febre                                                          | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| TOSSE      | Se gestante ou puérpera manifestou sintoma de tosse                                                          | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| GARGANTA   | Se gestante ou puérpera manifestou sintoma de dor de garganta                                                | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| DISPNEIA   | Se gestante ou puérpera manifestou sintoma de dispneia                                                       | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| DESC_RESP  | Se gestante ou puérpera manifestou sintoma de desconforto respiratório                                       | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| SATURACAO  | Se gestante ou puérpera manifestou sintoma de saturação                                                      | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| DIARREIA   | Se gestante ou puérpera manifestou sintoma de diarreia                                                       | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| VOMITO     | Se gestante ou puérpera manifestou sintoma de vômito                                                         | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| DOR_ABD    | Se gestante ou puérpera manifestou sintoma de dor abdominal                                                  | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| FADIGA     | Se gestante ou puérpera manifestou sintoma de fadiga                                                         | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| PERD_OLFT  | Se gestante ou puérpera manifestou sintoma de perda de olfato                                                | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| PERD_PALA  | Se gestante ou puérpera manifestou sintoma de perda de paladar                                               | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| ASMA       | Se gestante ou puérpera tem asma                                                                             | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| DIABETES   | Se gestante ou puérpera tem diabetes *mellitus*                                                              | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| NEUROLOGIC | Se gestante ou puérpera tem doença neurológica                                                               | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| PNEUMOPATI | Se gestante ou puérpera tem outra pneumopatia crônica                                                        | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| IMUNODEPRE | Se gestante ou puérpera tem imunodeficiência ou imunodepressão (diminuição da função do sistema imunológico) | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| RENAL      | Se gestante ou puérpera tem doença renal crônica                                                             | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| OBESIDADE  | Se gestante ou puérpera tem obesidade                                                                        | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| CARDIOPATI | Se gestante ou puérpera tem doença cardiovascular crônica                                                    | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| HEMATOLOGI | Se gestante ou puérpera tem doença hematológica crônica                                                      | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| HEPATICA   | Se gestante ou puérpera tem doença hepática crônica                                                          | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| VACINA_COV | Se gestante ou puérpera recebeu vacina COVID-19                                                              | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| DOSE_1_COV | Data em que gestante ou puérpera recebeu a 1ª dose da vacina COVID-19                                        | Dia/Mês/Ano                                                                                                                                                                      |
| DOSE_2_COV | Data em que gestante ou puérpera recebeu a 2ª dose da vacina COVID-19                                        | Dia/Mês/Ano                                                                                                                                                                      |
| FAB_COV_1  | Fabricante da vacina que a gestante ou puérpera recebeu na 1ª dose                                           |                                                                                                                                                                                  |
| FAB_COV_2  | Fabricante da vacina que a gestante ou puérpera recebeu na 2ª dose                                           |                                                                                                                                                                                  |
| SUPORT_VEN | Se gestante ou puérpera precisou de ventilação mecânica; se sim, se foi invasiva ou não                      | 1- sim, invasivo; 2- sim, não invasivo; 3- não; 9- ignorado                                                                                                                      |
| UTI        | Se gestante ou puérpera foi internada na UTI                                                                 | 1- sim; 2- não; 9- ignorado                                                                                                                                                      |
| DT_ENTUTI  | Data de entrada da gestante ou puérpera na UTI                                                               | Dia/Mês/Ano                                                                                                                                                                      |
| DT_SAIDUTI | Data de saída da gestante ou puérpera na UTI                                                                 | Dia/Mês/Ano                                                                                                                                                                      |
| EVOLUCAO   | Evolução do caso da gestante ou puérpera                                                                     | 1- cura; 2- óbito; 3- óbito por outras causas; 9- ignorado                                                                                                                       |

: Dicionário das variáveis da base de dados de COVID-19 em gestantes e puérperas. {#tbl-covid19}

### INDICADORES OBSTÉTRICOS

Consiste em um conjunto de dados com 5570 observações sobre indicadores obstétricos a nível municipal do ano de 2019, sendo os seguintes indicadores:

-   Prematuridade: Refere-se ao parto que ocorre em idade gestacional inferior a 37 semanas.

-   Gestação Múltipla: Diz respeito a uma gestação que gera dois ou mais fetos simultaneamente.

-   Parto Cesárea: Trata-se do tipo de parto em que a extração do feto é realizada por meio de intervenção cirúrgica.

-   Consultas de Pré-Natal: Consiste no acompanhamento médico realizado pela gestante durante a gravidez. O ideal é que ocorram pelo menos 7 consultas médicas durante o período de pré-natal.

-   Apgar: É uma escala proposta em 1953 pela médica Virgínia Apgar, que atribui pontuações a 5 sinais do recém-nascido: frequência cardíaca, respiração, tônus muscular, irritabilidade reflexa e cor da pele. A escala varia de 0 a 10, e escores abaixo de 7 requerem atenção dos profissionais obstetras. Essa avaliação é feita no primeiro minuto após o nascimento (Apgar do primeiro minuto) e novamente após 5 minutos (Apgar do quinto minuto).

-   Anomalia congênita: Refere-se a alterações estruturais ou funcionais que podem ser causadas por diversos fatores e têm origem durante a vida intrauterina.

A obtenção dos indicadores utilizados foi realizada considerando as frequências relativas ao município de residência dos nascidos vivos no ano da coleta. Os indicadores obstétricos são calculados como percentuais válidos, ou seja, os dados faltantes da variável em questão são desconsiderados. Por exemplo:

-   Percentual válido de prematuridade = (número de prematuros / número de nascidos vivos com informação de prematuridade) x 100.

O Dicionário para esse conjunto de dados é apresentado em @tbl-indicadores .

| Variável             | Descrição                                                          |
|--------------------|----------------------------------------------------|
| uf                   | Unidade Federativa (Estados + Distrito Federal)                    |
| municipio            | Município                                                          |
| codigo               | Código do município do IBGE                                        |
| nascidos_vivos       | Número de nascidos vivos                                           |
| porc_premat          | Percentual válido de prematuridade                                 |
| porc_gesta_multipla  | Percentual válido de gestações múltiplas                           |
| porc_cesarea         | Percentual válido de partos cesáreas                               |
| porc_0_consulta      | Percentual válido de nascidos com nenhuma consulta de pré-natal    |
| porc_7mais_consulta  | Percentual válido de nascidos com 7 ou mais consultas de pré-natal |
| porc_apgar1_menor_7  | Percentual válido de Apgar de 1º minuto menor que 7                |
| porc_apgar5_menor_7  | Percentual válido de Apgar de 5º minuto menor que 7                |
| porc_anomalia        | Percentual válido de nascidos com anomalia congênita               |
| porc_peso_menor_2500 | Percentual válido de nascidos com peso menor que 2.500 gramas      |
| porc_fem             | Percentual válido de nascidos do sexo feminino                     |

: Dicionário das variáveis da base de dados de Indicadores Obstétricos. {#tbl-indicadores}
